### PR TITLE
passthrough: make it work with binary data, closes #35

### LINKED ISSUE #35: passthrough response assumes text
```python
    aresponses.add(
        host=re.compile(r"127\.0\.0\.1:.*"), response=aresponses.passthrough
    )
```

But my content is binary (msgpack), therefore I get an exception:

```
web_protocol.py            355 ERROR    Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aresponses/main.py", line 60, in _handler
    return await self._find_response(request)
  File "/usr/local/lib/python3.7/site-packages/aresponses/main.py", line 98, in _find_response
    return await response(request)
  File "/usr/local/lib/python3.7/site-packages/aresponses/main.py", line 125, in passthrough
    text = await r.text()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1010, in text
    return self._body.decode(encoding, errors=errors)  # type: ignore
  File "/usr/local/lib/python3.7/encodings/cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2033: character maps to <undefined>
web_log.py                 233 INFO     127.0.0.1 [26/Nov/2019:19:20:08 +0000] "GET /u/2 HTTP/1.1" 500 1156 "-" "Python/3.7 aiohttp/3.5.4"
```
The problem lies in `text = await r.text()`, it should not assume the response is text.

### PR DESCRIPTION
**Pull request by gjcarneiro**
Sorry, I can't think of a public API service to test with, like httpstat.us, but in theory this should fix my problem and doesn't break the existing test.

### CODE REVIEW

**Comment by gjcarneiro** [comment]
Lint failed due to pre-existing CI problem.  The linter seems to not be properly installed...

**Comment by gjcarneiro** [comment]
ping

**Comment by brycedrennan** [comment]
I like the change.  I'll fix the lint issue and figure out if we need to increment the major version number for compatibility reasons.  

Thanks!

**Comment by brycedrennan** [comment]
Thanks for this improvement! I merged this change in #38

**Comment by brycedrennan** [comment]
Deployed to pypi: https://pypi.org/project/aresponses/1.1.2/

**Pull request closed without merging**
